name: rexipaymobile
description: "A new Flutter project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.3.3
  fl_chart: ^1.1.1
  lottie: ^3.1.0
  pinput: ^5.0.0
  country_picker: ^2.0.26
  intl: ^0.19.0
  local_auth: ^2.2.0
  image_picker: ^1.0.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
